version: "3.2"
services:
  php:
    build: './samplephpwebsite/'
    networks:
      - backend
    volumes:
      - ./samplephpwebsite/:/var/www/html/

  ngnix:
    image: nginx:1.12.0
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./samplephpwebsite/:/var/www/html/my_site

networks:
  backend:
    driver: bridge
