version: "3.2"
services:
  php:
    build: './samplephpwebsite/'
    networks:
      - backend
    volumes:
      - ./samplephpwebsite/:/var/www/html/my_site

  ngnix:
    image: nginx:1.12.0
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./samplephpwebsite/:/var/www/html/my_site
  db:
    image: mariadb:10.1
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sdrugntqqsciur
      - MYSQL_PASSWORD=sdrugntqqsciur
      - MYSQL_USER=php_user

networks:
  backend:
    driver: bridge
